### PR TITLE
fetched all the data from contributors.json file to .html file [Closes #37]

### LINKED ISSUE #37: fetch contributors details to contributors.html file
fetch all the data from contributors json file to contributors.html file
create a script.js file and fetch all data
comment if you are familiar with javascript fetch or map functions

### PR DESCRIPTION
**Pull request by MRIDUL-MB**
Please check this PR.

### CODE REVIEW

**Review by devvsakib — APPROVED** [review]
i cant see any real data, those are demo profile
image

**Review by devvsakib — CHANGES_REQUESTED** [review]
please add all data to contributors page

**Comment by MRIDUL-MB** [comment]
Oh, ok.

**Comment by MRIDUL-MB** [comment]
check now

**Review by devvsakib — APPROVED** [review]
amazing, dont forgot to add your details on json file

**Comment by MRIDUL-MB** [comment]
Sure!

**Pull request merged**
